### ISSUE TITLE
FetchError on server updating

### ISSUE THREAD

**Issue by Arcyvilk** [Arcyvilk/PointOnePercent#1]
```
{ FetchError: request to https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v1/?appid=293900&steamid=76561198066029713&key=API_KEY&format=json failed, reason: Parse Error
    at ClientRequest.<anonymous> (/var/www/PointOnePercent/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:160:13)
    at TLSSocket.socketOnData (_http_client.js:445:9)
    at TLSSocket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onread (net.js:602:20)
  name: 'FetchError',
  message: 'request to https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v1/?appid=293900&steamid=76561198066029713&key=API_KEY&format=json failed, reason: Parse Error',
  type: 'system',
  errno: 'HPE_INVALID_CONSTANT',
  code: 'HPE_INVALID_CONSTANT' }
error: Forever detected script was killed by signal: SIGKILL }
```

The structure of fetched API that returned Parse error: 

```
{
  "playerstats": {
    "steamID": "76561198066029713",
    "gameName": "Pivvot",
    "achievements": [
      {
        "apiname": "ACH_DIE_1000_TIMES",
        "achieved": 1,
        "unlocktime": 1493287548
      },
      {
        "apiname": "ACH_NO_DEATH_VOYAGE",
        "achieved": 1,
        "unlocktime": 1413645621
      },
      {
        "apiname": "ACH_NO_DEATH_EXPERT_VOYAGE",
        "achieved": 0,
        "unlocktime": 0
      },
      {
        "apiname": "ACH_FIVE_LOOPS_IN_ROW",
        "achieved": 1,
        "unlocktime": 1413466806
      },
      {
        "apiname": "ACH_ONE_DIRECTION_LOOPS",
        "achieved": 1,
        "unlocktime": 1413888236
      },
      {
        "apiname": "ACH_RANDOM_ENDLESS_SURVIVOR",
        "achieved": 1,
        "unlocktime": 1413569109
      },
      {
        "apiname": "ACH_RANDOM_EXPERT_ENDLESS_SURVIVOR",
        "achieved": 1,
        "unlocktime": 1493743984
      },
      {
        "apiname": "ACH_BERSERK_SURVIVOR",
        "achieved": 1,
        "unlocktime": 1493395664
      }
    ],
    "success": true
  }
}
```

**Comment by Arcyvilk** [comment]
Server restart and another attempt to update resulted in the same error appearing again, this time for player 25 while updating achievements from Cave Story

**Comment by Arcyvilk** [comment]
Another FetchError, this time triggered by GetOwnedGames endpoint

```
{ FetchError: invalid response body at: https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key=API_EY&steamid=76561198033628890 reason: unexpected end of file
data:    server.js:5545 -     at Gunzip.<anonymous> (/var/www/PointOnePercent/node_modules/node-fetch/lib/body.js:123:11)
data:    server.js:5545 -     at Gunzip.emit (events.js:160:13)
data:    server.js:5545 -     at Zlib.zlibOnError [as onerror] (zlib.js:145:8)
data:    server.js:5545 -   name: 'FetchError',
data:    server.js:5545 -   message: 'invalid response body at: https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key=API_KEY&steamid=76561198033628890 reason: unexpected end of file',
data:    server.js:5545 -   type: 'system',
data:    server.js:5545 -   errno: 'Z_BUF_ERROR',
data:    server.js:5545 -   code: 'Z_BUF_ERROR' }
```

**Comment by Arcyvilk** [comment]
Attempted to fix the HPE_INVALID_CONSTANT bug that occured in the first and second case by replacing all https occurences with http. Will continue monitoring the issue.

Still not knowing what was the reason for the Z_BUF_ERROR, might be because of Steam's profile being set up to private what triggered an invalid response, but it's only a suspection due to lack of data backing that theory up.
